### ISSUE TITLE
front-and-cal and rinex2assist  does not work.

### ISSUE THREAD

**Issue by Derso1** [gnss-sdr/gnss-sdr#815] opened 2024-10-10 19:01 UTC
Hi,
I am using rinex2assist to make the TCXO calibration using front-end-cal. It was possible to create the xml file with rinex2assist, but when I try to use the front-end-cal (SDR.SUPL_read_gps_assistance_xml=true), it is still broken because it requires the TOW (Time of Week) from SUPL (because the SUP does not work)

Somebody can help-me in this issue?

**Comment by Zi7ar21** [comment] 2024-10-12 04:04
Duplicate of #721 (@carlesfernandez, please re-open #721)

**Closed** 2024-10-25 09:09 UTC
