### ISSUE TITLE
Build errors on macOS

### ISSUE THREAD

**Issue by sdaheng** [gnss-sdr/gnss-sdr#373] opened 2020-05-10 15:03 UTC
Hello

I faced some problems when I tried to build with Xcode. 
After configure and generate with CMake. And opened Xcode project, ran "run_tests" . Compiler shows many errors.

**Here are some my environment information.**
OS version: macOS 10.15.4
Xcode version: 11.4.1
CMake version: 3.17.2

**CMake configure log**
The CXX compiler identification is AppleClang 11.0.3.11030032
The C compiler identification is AppleClang 11.0.3.11030032
Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ - works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang - works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Configuring GNSS-SDR v0.0.12 to be built on macOS Catalina 10.15
Build type set to Release.
Performing Test CMAKE_HAVE_LIBC_PTHREAD
Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
Checking for module 'gtest'
  No package 'gtest' found
Could NOT find GOOGLETEST (missing: LIBGTEST_DEV_DIR GTEST_INCLUDE_DIRS) 
Checking for GNU Radio Module: RUNTIME
 * INCLUDES=/opt/local/include
 * LIBS=/opt/local/lib/libgnuradio-runtime.dylib;/opt/local/lib/libgnuradio-pmt.dylib;/opt/local/lib/liblog4cpp.dylib
GNURADIO_RUNTIME_FOUND = TRUE
Checking for GNU Radio Module: PMT
 * INCLUDES=/opt/local/include
 * LIBS=/opt/local/lib/libgnuradio-runtime.dylib;/opt/local/lib/libgnuradio-pmt.dylib;/opt/local/lib/liblog4cpp.dylib
GNURADIO_PMT_FOUND = TRUE
Checking for GNU Radio Module: BLOCKS
 * INCLUDES=/opt/local/include
 * LIBS=/opt/local/lib/libgnuradio-blocks.dylib;/opt/local/lib/libgnuradio-runtime.dylib;/opt/local/lib/libgnuradio-pmt.dylib;/opt/local/lib/liblog4cpp.dylib
GNURADIO_BLOCKS_FOUND = TRUE
Checking for GNU Radio Module: FFT
 * INCLUDES=/opt/local/include
 * LIBS=/opt/local/lib/libgnuradio-fft.dylib;/opt/local/lib/libgnuradio-runtime.dylib;/opt/local/lib/libgnuradio-pmt.dylib;/opt/local/lib/liblog4cpp.dylib
GNURADIO_FFT_FOUND = TRUE
Checking for GNU Radio Module: FILTER
 * INCLUDES=/opt/local/include
 * LIBS=/opt/local/lib/libgnuradio-filter.dylib;/opt/local/lib/libgnuradio-fft.dylib;/opt/local/lib/libgnuradio-runtime.dylib;/opt/local/lib/libgnuradio-pmt.dylib;/opt/local/lib/liblog4cpp.dylib
GNURADIO_FILTER_FOUND = TRUE
Checking for GNU Radio Module: ANALOG
 * INCLUDES=/opt/local/include
 * LIBS=/opt/local/lib/libgnuradio-analog.dylib;/opt/local/lib/libgnuradio-runtime.dylib;/opt/local/lib/libgnuradio-pmt.dylib;/opt/local/lib/liblog4cpp.dylib;/opt/local/lib/libvolk.dylib
GNURADIO_ANALOG_FOUND = TRUE
Checking for GNU Radio Module: UHD
 * INCLUDES=/opt/local/include
 * LIBS=/opt/local/lib/libgnuradio-uhd.dylib;/opt/local/lib/libgnuradio-runtime.dylib;/opt/local/lib/libgnuradio-pmt.dylib;/opt/local/lib/liblog4cpp.dylib
GNURADIO_UHD_FOUND = TRUE
Found Boost: /usr/local/include (found suitable version "1.68.0", minimum required is "1.53") found components: atomic chrono date_time serialization system thread filesystem 
gflags library found at /opt/local/lib/libgflags.dylib
glog library found at /opt/local/lib/libglog.dylib
PugiXML include = /opt/local/include
PugiXML library = /opt/local/lib/libpugixml.dylib
CMake Warning at /Applications/CMake.app/Contents/share/cmake-3.17/Modules/FindProtobuf.cmake:500 (message):
  Protobuf compiler version 3.5.1 doesn't match library version 3.11.4
Call Stack (most recent call first):
  CMakeLists.txt:2000 (find_package)

Found Doxygen: /opt/local/bin/doxygen (found version "1.8.18") found components: doxygen dot 
Found LATEX: /opt/local/bin/latex  found components: PDFLATEX 
Doxygen found.
 You can build the documentation with 'xcodebuild doc'.
 When done, point your browser to /path_to/GNSS_SDR_Work/gnss-sdr-master/build/Xcode/html/index.html
 'xcodebuild pdfmanual' will generate a manual at /path_to/GNSS_SDR_Work/gnss-sdr-master/build/Xcode/docs/GNSS-SDR_manual.pdf
 'xcodebuild doc-clean' will clean the documentation.
NVIDIA CUDA GPU Acceleration will be not enabled.
 Enable it with 'cmake -DENABLE_CUDA=ON ..' to add support for GPU-based acceleration using CUDA.
Pcap include dirs set to /opt/local/include
Pcap library set to /opt/local/lib/libpcap.dylib
Highly-optimized custom UDP IP packet source is enabled.
 You can disable it with 'cmake -DENABLE_RAW_UDP=OFF ..'
FPGA offloading will be not enabled.
 Enable it with 'cmake -DENABLE_FPGA=ON ..' to add support for FPGA offloading.
Checking for module 'gnuradio-osmosdr'
  No package 'gnuradio-osmosdr' found
Could NOT find GROSMOSDR (missing: GROSMOSDR_LIBRARIES GROSMOSDR_INCLUDE_DIR) 
The (optional) driver for OsmoSDR and related front-ends is not enabled.
 Enable it with 'cmake -DENABLE_OSMOSDR=ON ..' to add support for OsmoSDR and other front-ends (HackRF, bladeRF, Realtek's RTL2832U-based USB dongles, etc.)
Checking for module 'gnuradio-iio'
  No package 'gnuradio-iio' found
Could NOT find GRIIO (missing: IIO_LIBRARIES IIO_INCLUDE_DIRS) 
Checking for module 'libad9361'
  No package 'libad9361' found
Could NOT find LIBAD9361 (missing: LIBAD9361_LIBRARIES LIBAD9361_INCLUDE_DIRS) 
Checking for module 'libiio'
  No package 'libiio' found
Could NOT find LIBIIO (missing: LIBIIO_LIBRARIES LIBIIO_INCLUDE_DIRS) 
The (optional) Teleorbit Flexiband front-end driver adapter is not enabled.
 Enable it with 'cmake -DENABLE_FLEXIBAND=ON ..' to add support for the Teleorbit Flexiband front-end.
Could NOT find TELEORBIT (missing: TELEORBIT_LIBRARIES TELEORBIT_INCLUDE_DIRS) 
Checking for module 'gr-gn3s'
  No package 'gr-gn3s' found
The (optional and experimental) GN3S driver is not enabled.
 Enable it with 'cmake -DENABLE_GN3S=ON ..' to add support for the GN3S dongle.
Checking for module 'gr-dbfcttc'
  No package 'gr-dbfcttc' found
The (optional) CTTC's Antenna Array front-end driver is not enabled.
 Enable it with 'cmake -DENABLE_ARRAY=ON ..' to add support for the CTTC experimental array front-end.
Could NOT find GPERFTOOLS (missing: GPERFTOOLS_LIBRARIES GPERFTOOLS_INCLUDE_DIR GPERFTOOLS_TCMALLOC GPERFTOOLS_PROFILER) 
clang-tidy not found.
Could NOT find Gnuplot (missing: GNUPLOT_EXECUTABLE) 

***************************************
*           SUMMARY REPORT            *
***************************************

Building on macOS Catalina 10.15
CMake version: 3.17.2
The CXX compiler identification is AppleClang 11.0.3.11030032
The C compiler identification is AppleClang 11.0.3.11030032

The following REQUIRED packages have been found:

 * GNURADIO, The free and open software radio ecosystem (found: v3.7.13.5), <https://www.gnuradio.org/>
   Implements flowgraph scheduler, provides some processing blocks and classes to create new ones.
 * LOG4CPP, Library of C++ classes for flexible logging (found: v1.1, C++17-ready), <http://log4cpp.sourceforge.net/>
   Required by GNU Radio.
 * Boost (required version >= 1.53), Portable C++ source libraries (found: v1.68.0), <https://www.boost.org>
   Used widely across the source code.
 * VOLK, Vector-Optimized Library of Kernels (found: v2.2.1), <https://www.libvolk.org>
   Provides an abstraction of optimized math routines targeting several SIMD processors.
 * VOLKGNSSSDR, Vector-Optimized Library of Kernels for GNSS-SDR (found: v0.0.12).
   Accelerates math routines targeting several SIMD processors.
 * GFLAGS, C++ library that implements commandline flags processing (found: v2.2.2), <https://github.com/gflags/gflags>
   Used for commandline flags management.
 * GLOG, C++ implementation of the Google logging module (found: v0.4.0), <https://github.com/google/glog>
   Used for runtime internal logging.
 * Armadillo, C++ library for linear algebra and scientific computing (found: v9.870.2), <http://arma.sourceforge.net/>
   Used for matrix computations.
 * GnuTLS, Transport Layer Security Library (found: v3.6.13), <https://www.gnutls.org/>
   Used for the SUPL protocol implementation.
 * MATIO, MATLAB MAT File I/O Library (found: v1.5.17), <https://github.com/tbeu/matio>
   Used to store processing block's results in MAT files readable from MATLAB/Octave.
 * PUGIXML, Light-weight, simple and fast XML parser for C++, <https://pugixml.org/>
   Used to handle Galileo almanac XML files published by the European GNSS Service Centre.
 * Threads, Implements the POSIX Threads execution model, <https://computing.llnl.gov/tutorials/pthreads/>
   Used to implement parallelism.
 * Protobuf, Structured data serialization mechanism (found: v3.11.4), <https://developers.google.com/protocol-buffers/>
   Used to serialize output data in a way that can be read by other applications.

-- The following REQUIRED packages have not been found:

 * GOOGLETEST, Source code of Google's Testing Framework, <https://github.com/google/googletest>
   Used for Unit and System Tests.
   Googletest v1.10.0 will be downloaded and built when doing 'xcodebuild'.

-- The following OPTIONAL packages have been found:

 * UHD, USRP Hardware Driver (found: v3.15.0.0-MacPorts-Release), <https://www.ettus.com/sdr-software/uhd-usrp-hardware-driver/>
   Used for communication with front-ends of the USRP family.
 * Doxygen, Generates documentation from annotated C++ sources (found: v1.8.18), <http://www.doxygen.nl>
   Used to generate code documentation by doing 'xcodebuild doc'
 * LATEX, High-quality typesetting system, <https://www.latex-project.org>
   Used to generate a PDF manual by doing 'xcodebuild pdfmanual'
 * PCAP, A portable C/C++ library for network traffic capture (found: v1.9.1), <https://www.tcpdump.org>
   Used for the custom UDP IP packet source.

-- The following OPTIONAL packages have not been found:

 * GROSMOSDR, osmocom GNU Radio blocks, <https://osmocom.org/projects/gr-osmosdr/wiki>
   Used for communication with OsmoSDR and other front-ends (HackRF, bladeRF, Realtek's RTL2832U-based dongles, etc.).
 * GRIIO, IIO blocks for GNU Radio, <https://github.com/analogdevicesinc/gr-iio>
   Used for communication with PlutoSDR and FMCOMMS devices.
 * LIBAD9361, A library for interfacing with AD936X RF transceivers, <https://github.com/analogdevicesinc/libad9361-iio>
   Used for configuring devices with the AD9361 chipset.
 * LIBIIO, A library for interfacing with Linux IIO devices, <https://github.com/analogdevicesinc/libiio>
   Used for communication with the AD9361 chipset.
 * TELEORBIT, The Teleorbit's Flexiband GNU Radio block.
   Used for communication with the Flexiband front-end.
 * GPERFTOOLS, Collection of performance analysis tools, <https://github.com/gperftools/gperftools>
   Used for performance analysis.
 * Gnuplot, A portable command-line driven graphing utility, <http://www.gnuplot.info>
   Used to generate plots in some tests.

-- The following features have been enabled:

 * ENABLE_UHD, Enables UHD_Signal_Source for using RF front-ends from the USRP family. Requires gr-uhd.
 * ENABLE_RAW_UDP, Enables Custom_UDP_Signal_Source for custom UDP packet sample source. Requires libpcap.
 * ENABLE_LOG, Enables runtime internal logging with Google glog.
 * ENABLE_UNIT_TESTING, Enables building of Unit Tests.

-- The following features have been disabled:

 * ENABLE_OSMOSDR, Enables Osmosdr_Signal_Source and RtlTcp_Signal_Source for using RF front-ends compatible with the OsmoSDR driver. Requires gr-osmosdr.
 * ENABLE_FMCOMMS2, Enables Fmcomms2_Signal_Source for FMCOMMS2/3/4 devices. Requires gr-iio and libad9361-dev.
 * ENABLE_PLUTOSDR, Enables Plutosdr_Signal_Source for using ADALM-PLUTO boards. Requires gr-iio.
 * ENABLE_AD9361, Enables Ad9361_Fpga_Signal_Source for devices with the AD9361 chipset. Requires libiio and libad9361-dev.
 * ENABLE_FLEXIBAND, Enables Flexiband_Signal_Source for using Teleorbit's Flexiband RF front-end. Requires gr-teleorbit.
 * ENABLE_GN3S, Enables Gn3s_Signal_Source for using the GN3S v2 dongle. Requires gr-gn3s.
 * ENABLE_ARRAY, Enables Raw_Array_Signal_Source and Array_Signal_Conditioner for using CTTC's antenna array. Requires gr-dbfcttc.
 * ENABLE_GPERFTOOLS, Enables performance analysis. Requires Gperftools.
 * ENABLE_GPROF, Enables performance analysis with 'gprof'.
 * ENABLE_CLANG_TIDY, Runs clang-tidy along with the compiler. Requires Clang.
 * ENABLE_PROFILING, Runs volk_gnsssdr_profile at the end of the building.
 * ENABLE_OPENCL, Enables GPS_L1_CA_PCPS_OpenCl_Acquisition (experimental). Requires OpenCL.
 * ENABLE_CUDA, Enables GPS_L1_CA_DLL_PLL_Tracking_GPU (experimental). Requires CUDA.
 * ENABLE_FPGA, Enables building of processing blocks for FPGA offloading.
 * ENABLE_ARMA_NO_DEBUG, Enables passing the ARMA_NO_DEBUG macro to Armadillo, hence disabling bound checking.
 * ENABLE_GENERIC_ARCH, When disabled, flags such as '-march=native' are passed to the compiler.
 * ENABLE_PACKAGING, Enables software packaging.
 * ENABLE_OWN_GLOG, Forces the downloading and building of Google glog.
 * ENABLE_OWN_ARMADILLO, Forces the downloading and building of Armadillo.
 * ENABLE_UNIT_TESTING_MINIMAL, Enables building a minimal set of Unit Tests.
 * ENABLE_UNIT_TESTING_EXTRA, Enables building of Extra Unit Tests and downloading of external data files.
 * ENABLE_SYSTEM_TESTING, Enables building of System Tests.
 * ENABLE_SYSTEM_TESTING_EXTRA, Enables building of Extra System Tests and downloading of external tools.
 * ENABLE_OWN_GPSTK, Forces the downloading and building of GPSTk for system tests.
 * ENABLE_GNSS_SIM_INSTALL, Enables downloading and building of gnss-sim.
 * ENABLE_INSTALL_TESTS, Install test binaries when doing 'xcodebuild install'.

GNSS-SDR v0.0.12 is ready to be built.
Configuring done
Generating done

**Compliler errors**
ompileC build/Xcode/src/core/system_parameters/gnss-sdr.build/Debug/core_system_parameters.build/Objects-normal/x86_64/beidou_dnav_almanac.o src/core/system_parameters/beidou_dnav_almanac.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
    cd /path_to/GNSS_SDR_Work/gnss-sdr-master
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -target x86_64-apple-macos10.15 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c++1z -stdlib=libc++ -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wno-shorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -DCMAKE_INTDIR=\"Debug\" -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -g -Wno-sign-conversion -Wno-infinite-recursion -Wno-move -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-range-loop-analysis -Wno-semicolon-before-method-body -index-store-path /path_to/Library/Developer/Xcode/DerivedData/gnss-sdr-fqrumiagcihxfncqwckqznvthwnt/Index/DataStore -I/path_to/GNSS_SDR_Work/gnss-sdr-master/build/Xcode/src/core/system_parameters/Debug/include -isystem /usr/local/include -isystem /opt/local/include -isystem /opt/local/include/glog -I/path_to/GNSS_SDR_Work/gnss-sdr-master/build/Xcode/src/core/system_parameters/gnss-sdr.build/Debug/core_system_parameters.build/DerivedSources-normal/x86_64 -I/path_to/GNSS_SDR_Work/gnss-sdr-master/build/Xcode/src/core/system_parameters/gnss-sdr.build/Debug/core_system_parameters.build/DerivedSources/x86_64 -I/path_to/GNSS_SDR_Work/gnss-sdr-master/build/Xcode/src/core/system_parameters/gnss-sdr.build/Debug/core_system_parameters.build/DerivedSources -F/path_to/GNSS_SDR_Work/gnss-sdr-master/build/Xcode/src/core/system_parameters/Debug -Og -fstandalone-debug -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wextra -march=native -std=c++14 -MMD -MT dependencies -MF /path_to/GNSS_SDR_Work/gnss-sdr-master/build/Xcode/src/core/system_parameters/gnss-sdr.build/Debug/core_system_parameters.build/Objects-normal/x86_64/beidou_dnav_almanac.d --serialize-diagnostics /path_to/GNSS_SDR_Work/gnss-sdr-master/build/Xcode/src/core/system_parameters/gnss-sdr.build/Debug/core_system_parameters.build/Objects-normal/x86_64/beidou_dnav_almanac.dia -c /path_to/GNSS_SDR_Work/gnss-sdr-master/src/core/system_parameters/beidou_dnav_almanac.cc -o /path_to/GNSS_SDR_Work/gnss-sdr-master/build/Xcode/src/core/system_parameters/gnss-sdr.build/Debug/core_system_parameters.build/Objects-normal/x86_64/beidou_dnav_almanac.o

In file included from/path_to/GNSS_SDR_Work/gnss-sdr-master/src/core/system_parameters/beidou_dnav_almanac.cc:22:
In file included from /path_tos/GNSS_SDR_Work/gnss-sdr-master/src/core/system_parameters/beidou_dnav_almanac.h:25:
In file included from /usr/local/include/boost/serialization/nvp.hpp:19:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/utility:204:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdint:157:8: error: no member named 'uint8_t' in the global namespace
using::uint8_t;
     ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdint:158:8: error: no member named 'uint16_t' in the global namespace
using::uint16_t;
     ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdint:159:8: error: no member named 'uint32_t' in the global namespace
using::uint32_t;
     ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdint:160:8: error: no member named 'uint64_t' in the global namespace
using::uint64_t;
     ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdint:162:8: error: no member named 'int_least8_t' in the global namespace
using::int_least8_t;
     ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdint:163:8: error: no member named 'int_least16_t' in the global namespace
using::int_least16_t;
     ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdint:164:8: error: no member named 'int_least32_t' in the global namespace
using::int_least32_t;
     ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdint:165:8: error: no member named 'int_least64_t' in the global namespace
using::int_least64_t;
     ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdint:167:8: error: no member named 'uint_least8_t' in the global namespace
using::uint_least8_t;
     ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdint:168:8: error: no member named 'uint_least16_t' in the global namespace
using::uint_least16_t;
     ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdint:169:8: error: no member named 'uint_least32_t' in the global namespace
using::uint_least32_t;
     ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdint:170:8: error: no member named 'uint_least64_t' in the global namespace
using::uint_least64_t;
     ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdint:172:8: error: no member named 'int_fast8_t' in the global namespace
using::int_fast8_t;
     ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdint:173:8: error: no member named 'int_fast16_t' in the global namespace
using::int_fast16_t;
     ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdint:174:8: error: no member named 'int_fast32_t' in the global namespace
using::int_fast32_t;
     ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdint:175:8: error: no member named 'int_fast64_t' in the global namespace
using::int_fast64_t;
     ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdint:177:8: error: no member named 'uint_fast8_t' in the global namespace
using::uint_fast8_t;
     ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdint:178:8: error: no member named 'uint_fast16_t' in the global namespace
using::uint_fast16_t;
     ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdint:179:8: error: no member named 'uint_fast32_t' in the global namespace
using::uint_fast32_t;
     ~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.

**I also tried to set c++ standard library to libstdc++, c++ language dialect to gnu++14. But it shows many others problem, like 'cstddef' not found, 'utility' not found, etc. And I manually add c++ path to system header search path, but it didn`t work.**

Thanks a lot for any help.

**Comment by carlesfernandez** [comment] 2020-05-11 08:46
Dear @sdaheng ,

I've just reproduced the same process, with the same setup, and Xcode can compile the code successfully:

```
$ cmake -GXcode ..
...

-- ***************************************
-- *           SUMMARY REPORT            *
-- ***************************************
-- 
-- Building on macOS Catalina 10.15
-- CMake version: 3.17.2
-- The CXX compiler identification is AppleClang 11.0.3.11030032
-- The C compiler identification is AppleClang 11.0.3.11030032
```

and then:
```
$ xcodebuild
```

or directly building from Xcode. In both cases, it works well.

I don't know what could be the problem in your setup. Did you have installed Xcode's Command Line Tools?

**Comment by sdaheng** [comment] 2020-05-11 09:24
Thanks very much for your reply.
Yes, I installed Xcode command line tools. I tried your method, and it
works.

I used CMake application not command yesterday. It seems that configured by
CMake application will cause compile errors? Any idea about why it happened?

I also want to know that If I integrate it into my project, I just use
those libs that Xcode built?

Carles Fernandez <notifications@github.com> 于2020年5月11日周一 下午4:46写道：

**Comment by carlesfernandez** [comment] 2020-05-11 10:08
Hi,

I always use CMake from the command line, so I don't know the peculiarities of the GUI. Probably is something related to the configuration.

Related to including the generated libs in another project, gnss-sdr is not really thought as a library but an application. But if you link your code against the generated static libs, and add to your project the paths of the required .h files, it should work. You probably will need to include into your project the dependencies of those static libs (e.g., GNURADIO, GLOG, GFLAGS, etc.).

Hope this helps!

**Comment by sdaheng** [comment] 2020-05-11 10:18
Yeah, Its really help me. I will think about how to use this for my
research project😁. Thanks again for your help.

Carles Fernandez <notifications@github.com> 于2020年5月11日周一 下午6:08写道：

**Comment by carlesfernandez** [comment] 2020-05-11 10:26
Great! Good luck with your project!

I'm closing this issue since it seems resolved, feel free to open a new one if other problems arise.

**Closed by carlesfernandez** 2020-05-11 10:26 UTC
